<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mula</string>
	</array>
	<key>name</key>
	<string>Mula</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>&lt;%</string>
			<key>comment</key>
			<string>other languages</string>
			<key>end</key>
			<string>%&gt;</string>
			<key>name</key>
			<string>support.function</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>%=([a-zA-Z]+[_a-zA-Z0-9]*)</string>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\(\*</string>
			<key>comment</key>
			<string>comments</string>
			<key>end</key>
			<string>\*\)</string>
			<key>name</key>
			<string>comment.block</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>reserved words</string>
			<key>match</key>
			<string>(run|out)</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>operators</string>
			<key>match</key>
			<string>(\-\&gt;|\&lt;\-|\+|\-|\*|\/|\=)</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>strings</string>
			<key>match</key>
			<string>(\'.*\')</string>
			<key>name</key>
			<string>string.quoted</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>variables</string>
			<key>match</key>
			<string>([a-zA-Z]+[_a-zA-Z0-9]*)</string>
			<key>name</key>
			<string>entity.name.type</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>integers</string>
			<key>match</key>
			<string>\d+</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.mula</string>
	<key>uuid</key>
	<string>4c5f0867-bb81-408f-a2f9-2765cfdaf415</string>
</dict>
</plist>
